USE TESTE
GO

ALTER PROCEDURE dbo.CAD_CLI_SP_INSERIR_DADOS
AS
	BEGIN

		-- Deleta clientes duplicados da tabela temporaria (planilha)
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
		FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
		INNER JOIN (
			SELECT CPF_CLIENTE
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
			GROUP BY CPF_CLIENTE
			HAVING COUNT(*) > 1
		) DUPLICATES
		ON TEMP.CPF_CLIENTE = DUPLICATES.CPF_CLIENTE

		-- Deletando clientes que possuem telefones duplicados da tabela temporaria (planilha)
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
		FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
		INNER JOIN (
			SELECT NUMERO_DDD, NUMERO_TELEFONE
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
			GROUP BY NUMERO_DDD, NUMERO_TELEFONE
			HAVING COUNT(*) > 1
		) DUPLICATES
		ON TEMP.NUMERO_DDD = DUPLICATES.NUMERO_DDD
		AND TEMP.NUMERO_TELEFONE = DUPLICATES.NUMERO_TELEFONE

		-- Deletando clientes que possuem e-mails duplicados da tabela temporaria (planilha)
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
		FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
		INNER JOIN (
			SELECT ENDERECO_EMAIL
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
			GROUP BY ENDERECO_EMAIL
			HAVING COUNT(*) > 1
		) DUPLICATES
		ON TEMP.ENDERECO_EMAIL = DUPLICATES.ENDERECO_EMAIL

		-- Deleta clientes que já estão inseridos na tabela de cliente.
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
		FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
		INNER JOIN CAD_CLI_TBL_CLIENTE AS CLI
			ON CLI.CPF_CLIENTE = SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1)
			AND CLI.CPF_CONTROLE = RIGHT(TEMP.CPF_CLIENTE, 2)

		-- Inserindo novos clientes
		INSERT INTO dbo.CAD_CLI_TBL_CLIENTE
			SELECT 
				TEMP.NOME_CLIENTE,
				SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) AS CPF_CLIENTE,
				RIGHT(TEMP.CPF_CLIENTE, 2) AS CPF_CONTROLE,
				TEMP.DATA_NASCIMENTO
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP	
			GROUP BY
				TEMP.NOME_CLIENTE,
				SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1),
				RIGHT(TEMP.CPF_CLIENTE, 2),
				TEMP.DATA_NASCIMENTO

		-- Inserindo novos endereços
		INSERT INTO dbo.CAD_CLI_TBL_ENDERECO
			SELECT 
				CLI.ID_CLIENTE,
				TEMP.LOGRADOURO,
				TEMP.NUMERO_RUA,
				TEMP.COMPLEMENTO,
				TEMP.BAIRRO,
				TEMP.CIDADE,
				TEMP.UF,
				TEMP.CEP
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
			INNER JOIN dbo.CAD_CLI_TBL_CLIENTE AS CLI
				ON TEMP.NOME_CLIENTE = CLI.NOME_CLIENTE
				AND SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) = CLI.CPF_CLIENTE
				AND RIGHT(TEMP.CPF_CLIENTE, 2) = CLI.CPF_CONTROLE
				AND TEMP.DATA_NASCIMENTO = CLI.DATA_NASCIMENTO
			GROUP BY
				CLI.ID_CLIENTE,
				TEMP.LOGRADOURO,
				TEMP.NUMERO_RUA,
				TEMP.COMPLEMENTO,
				TEMP.BAIRRO,
				TEMP.CIDADE,
				TEMP.UF,
				TEMP.CEP
		
		-- Deletando telefones duplicados
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
			INNER JOIN dbo.CAD_CLI_TBL_CLIENTE AS CLI
				ON TEMP.NOME_CLIENTE = CLI.NOME_CLIENTE
				AND SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) = CLI.CPF_CLIENTE
				AND RIGHT(TEMP.CPF_CLIENTE, 2) = CLI.CPF_CONTROLE
				AND TEMP.DATA_NASCIMENTO = CLI.DATA_NASCIMENTO
			INNER JOIN dbo.CAD_CLI_TBL_TELEFONE AS TEL
				ON TEMP.NUMERO_DDD = TEL.NUMERO_DDD
				AND TEMP.NUMERO_TELEFONE = TEL.NUMERO_TELEFONE

		-- Inserindo novos telefones
		INSERT INTO dbo.CAD_CLI_TBL_TELEFONE
			SELECT 
				CLI.ID_CLIENTE,
				55 AS NUMERO_PAIS,
				TEMP.NUMERO_DDD,
				TEMP.NUMERO_TELEFONE
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
			INNER JOIN dbo.CAD_CLI_TBL_CLIENTE AS CLI
				ON TEMP.NOME_CLIENTE = CLI.NOME_CLIENTE
				AND SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) = CLI.CPF_CLIENTE
				AND RIGHT(TEMP.CPF_CLIENTE, 2) = CLI.CPF_CONTROLE
				AND TEMP.DATA_NASCIMENTO = CLI.DATA_NASCIMENTO
			GROUP BY
				CLI.ID_CLIENTE,
				TEMP.NUMERO_DDD,
				TEMP.NUMERO_TELEFONE

		-- Deletando e-mails duplicados
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
			INNER JOIN dbo.CAD_CLI_TBL_CLIENTE AS CLI
				ON TEMP.NOME_CLIENTE = CLI.NOME_CLIENTE
				AND SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) = CLI.CPF_CLIENTE
				AND RIGHT(TEMP.CPF_CLIENTE, 2) = CLI.CPF_CONTROLE
				AND TEMP.DATA_NASCIMENTO = CLI.DATA_NASCIMENTO
			INNER JOIN dbo.CAD_CLI_TBL_EMAIL AS EM
				ON TEMP.ENDERECO_EMAIL = EM.ENDERECO_EMAIL

		-- Inserindo novos e-mails
		INSERT INTO dbo.CAD_CLI_TBL_EMAIL
			SELECT 
				CLI.ID_CLIENTE,
				TEMP.ENDERECO_EMAIL
			FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP AS TEMP
			INNER JOIN dbo.CAD_CLI_TBL_CLIENTE AS CLI
				ON TEMP.NOME_CLIENTE = CLI.NOME_CLIENTE
				AND SUBSTRING(TEMP.CPF_CLIENTE, 0, LEN(TEMP.CPF_CLIENTE) - 1) = CLI.CPF_CLIENTE
				AND RIGHT(TEMP.CPF_CLIENTE, 2) = CLI.CPF_CONTROLE
				AND TEMP.DATA_NASCIMENTO = CLI.DATA_NASCIMENTO
			GROUP BY 
				CLI.ID_CLIENTE,
				TEMP.ENDERECO_EMAIL

		-- Deletar dados da tabela temporaria
		DELETE FROM dbo.CAD_CLI_TBL_CLIENTE_BULKCOPY_TEMP

	END
GO

GRANT EXECUTE ON dbo.CAD_CLI_SP_INSERIR_DADOS TO guest;
GO